# Generated by Django 3.2.16 on 2024-03-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
