# Generated by Django 4.2.7 on 2024-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odered_Product',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
