# Generated by Django 4.2.7 on 2024-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0,null=True)),
                ('caption', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
