# Generated by Django 4.2.7 on 2024-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_user',
            field=models.TextField(null=True),
        ),
    ]
